### ISSUE TITLE
MySQL Error on Activation

### ISSUE THREAD

**Issue by 4czr** [snlbaral/MyBB-Registration-Invite-Only#1]
Trying to install this plugin to my board and it straight away throws a standard MyBB MySQL error at me with no error reporting to help.

**Comment by snlbaral** [comment]
Is there any sql error reported? if you could provide bit more detail of that error

**Comment by x0rp01s0n** [comment]
```
SQL Error:
    1366 - Incorrect integer value: '' for column `dbname`.`mybb_settinggroups`.`gid` at row 1
Query:
    INSERT INTO mybb_settinggroups (`gid`,`name`,`title`,`description`,`disporder`,`isdefault`) VALUES ('','doinviteonly','MyBB Registration Invite Only','Settings for MyBB Registration Invite Only','1','0') 
```
    this is the error you get when trying to install hope you fix it im to lazy xD

**Comment by x0rp01s0n** [comment]
never mind i fixed it you had to cast the values in mysql instead of sending them as string
```
$doinviteonly_group = array(
        'gid' => '',
        'name' => 'doinviteonly',
        'title' => 'MyBB Registration Invite Only',
        'description' => 'Settings for MyBB Registration Invite Only',
        'disporder' => '1',
        'isdefault' =>  '0',
    );
```
should be
```
$doinviteonly_group = array(
        'gid' => (int)'',
        'name' => 'doinviteonly',
        'title' => 'MyBB Registration Invite Only',
        'description' => 'Settings for MyBB Registration Invite Only',
        'disporder' => '1',
        'isdefault' =>  '0',
    );
```

**Comment by snlbaral** [comment]
This issue seems to be on MySql server running in STRICT MODE most probably. glad you found the solution yourself. The issue can be resolved in two way.
1. Easy fix as you have found and mentioned above.
2. By removing/disabling STRICT MODE in MySQL
