### ISSUE TITLE
Invite codes not deleting

### ISSUE THREAD

**Issue by sndcode** [snlbaral/MyBB-Registration-Invite-Only#3]
Hi , thank you for the effort ! 
I really enjoy the plugin , but theres a problem.
When i give someone an invite code, he uses it to register it will still be in my list of invite codes.
Would be nice if the code gets deleted from my User CP when it was used :) 

Thanks in advance!

**Comment by sndcode** [comment]
just updated my plugin since i saw this github was updated 8 days ago and now its working. Anyways , thanks! 
Also is it possible to log which user registered on which code ? 
Possible to set normal user can only generate 3 codes every month ?

**Comment by snlbaral** [comment]
Yes. it is possible to do that. I'll add such option in next version. You can find update or drop your suggestions for the plugin here:
https://community.mybb.com/thread-230714.html
